// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.7
// 	protoc        v6.31.1
// source: math.proto

package main

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MathRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Num1          int64                  `protobuf:"varint,1,opt,name=num1,proto3" json:"num1,omitempty"`
	Num2          int64                  `protobuf:"varint,2,opt,name=num2,proto3" json:"num2,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MathRequest) Reset() {
	*x = MathRequest{}
	mi := &file_math_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MathRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MathRequest) ProtoMessage() {}

func (x *MathRequest) ProtoReflect() protoreflect.Message {
	mi := &file_math_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MathRequest.ProtoReflect.Descriptor instead.
func (*MathRequest) Descriptor() ([]byte, []int) {
	return file_math_proto_rawDescGZIP(), []int{0}
}

func (x *MathRequest) GetNum1() int64 {
	if x != nil {
		return x.Num1
	}
	return 0
}

func (x *MathRequest) GetNum2() int64 {
	if x != nil {
		return x.Num2
	}
	return 0
}

type MathResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Reply         int64                  `protobuf:"varint,1,opt,name=reply,proto3" json:"reply,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MathResponse) Reset() {
	*x = MathResponse{}
	mi := &file_math_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MathResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MathResponse) ProtoMessage() {}

func (x *MathResponse) ProtoReflect() protoreflect.Message {
	mi := &file_math_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MathResponse.ProtoReflect.Descriptor instead.
func (*MathResponse) Descriptor() ([]byte, []int) {
	return file_math_proto_rawDescGZIP(), []int{1}
}

func (x *MathResponse) GetReply() int64 {
	if x != nil {
		return x.Reply
	}
	return 0
}

var File_math_proto protoreflect.FileDescriptor

const file_math_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"math.proto\x12\x04main\"5\n" +
	"\vMathRequest\x12\x12\n" +
	"\x04num1\x18\x01 \x01(\x03R\x04num1\x12\x12\n" +
	"\x04num2\x18\x02 \x01(\x03R\x04num2\"$\n" +
	"\fMathResponse\x12\x14\n" +
	"\x05reply\x18\x01 \x01(\x03R\x05reply2o\n" +
	"\vMathService\x12.\n" +
	"\x03Sum\x12\x11.main.MathRequest\x1a\x12.main.MathResponse\"\x00\x120\n" +
	"\x05Multi\x12\x11.main.MathRequest\x1a\x12.main.MathResponse\"\x00B\x03Z\x01.b\x06proto3"

var (
	file_math_proto_rawDescOnce sync.Once
	file_math_proto_rawDescData []byte
)

func file_math_proto_rawDescGZIP() []byte {
	file_math_proto_rawDescOnce.Do(func() {
		file_math_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_math_proto_rawDesc), len(file_math_proto_rawDesc)))
	})
	return file_math_proto_rawDescData
}

var file_math_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_math_proto_goTypes = []any{
	(*MathRequest)(nil),  // 0: main.MathRequest
	(*MathResponse)(nil), // 1: main.MathResponse
}
var file_math_proto_depIdxs = []int32{
	0, // 0: main.MathService.Sum:input_type -> main.MathRequest
	0, // 1: main.MathService.Multi:input_type -> main.MathRequest
	1, // 2: main.MathService.Sum:output_type -> main.MathResponse
	1, // 3: main.MathService.Multi:output_type -> main.MathResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_math_proto_init() }
func file_math_proto_init() {
	if File_math_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_math_proto_rawDesc), len(file_math_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_math_proto_goTypes,
		DependencyIndexes: file_math_proto_depIdxs,
		MessageInfos:      file_math_proto_msgTypes,
	}.Build()
	File_math_proto = out.File
	file_math_proto_goTypes = nil
	file_math_proto_depIdxs = nil
}
